### PR TITLE
Design teardown

### PR DESCRIPTION
**Pull request by Jhdezj**
This is my last version of project 5 for review.  It includes the full teardown of [https://www.smashingmagazine.com/](https://www.smashingmagazine.com/)

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 🐱

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Nice Job @Jhdezj  🎉🎉

You did quite well using HTML5 semantics in your code.👍

However, kindly explain why you are the only contributor whereas the project is supposed to be collaborative.

Also, there are a few changes that need to be made before moving forward.👇

- [x] Required - Kindly fix the HTML validation error on your code using this [tool](https://validator.w3.org/nu/).

- [x] Required - Also a design teardown is supposed to used shades of gray to depict visual hierarchy, yet your page has white backgrounds, kindly use shades of gray.

- [x] Required - Your page needs to cover the full dimensions of the screen.
**THIS IS YOURS**👇
Inkedice_screenshot_20200402-093618_LI

The areas circled in red should be filled by the page.

- [x] Required - On the original webpage, the section just before the footer is covered by a full width subscribe template, but this looks different in yours, kindly fix this.
**THIS IS YOURS👇**
ice_screenshot_20200402-094542

**THIS IS WHAT THE ORIGINAL LOOKS LIKE👇**
ice_screenshot_20200402-094526

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAVE A SMASHING CODING DAY!👨‍💻

**Comment by Jhdezj** [comment]
Hey @mikenath223 . I worked on your suggestions and this is what I have so far: 

1.- I am working by myself on this and the next projects because I didn't apply for repairing as I have been facing some personal issues lately. I will stick to the program in what follows though. 

2.- I validated my code already. 

3.- I fixed my heatmap by coloring all the sections in a grayscale. 

4.- The page doesn't cover the full dimension of big screens because I based my heat map on a view of a1360x760 display. 

Thanks for the review
Jhdez

**Comment by thsvr** [comment]
### **STATUS: CHANGES REQUIRED** :muscle: :muscle: 

Hi @Jhdezj :smile: 
Congrats for the hard work and for did most of the requirements from Mike(TSE). You are almost there :muscle: 

**As required by Mike,** 
_''On the original webpage, the section just before the footer is covered by a full width subscribe template, but this looks different in yours...''_ 
**Can you please fix it and then request another review?**


:v: On the first pull request, it is also required to add a short summary that describes what you did on the project. Can you please consider it on the next ''first' pull request?
### You did it perfectly on the pull request for this re-review :1st_place_medal: 

If you have any questions, don't hesitate to contact me through slack [@thaís Vieira Azevedo](url)


### **Happy coding and good luck on the next review** :computer: 

_Project reviewed by Thaís Vieira (TSE)_

**Comment by Jhdezj** [comment]
Hello @mikenath223 and @thsvr . I added some clarifications on the readme file. It's about displaying differences due to site responsiveness. I hope this solves the issue of why the project looks different than the original.   

Thanks for the review 
Jhdezj

**Review by men32z — APPROVED** [review]
### hey @Jhdezj !
in the next projects try to add a more descriptive PR I know that maybe sounds redundant in a short project but you have to practice describing features of you PR.

BlgS1sdIUAEybkW

### Status Approved

--Luis Preza

**Pull request merged**
